### ISSUE TITLE
Cable physics: tension, torsion, self-collision

### ISSUE THREAD

**Issue by parkerhams** [parkerhams/grandma-game#11]
- [x] Script cable physics and relationships with Joints
- [x] Deploy on Oculus Quest
- [x] Have limitations on cable length
- [ ] Try using Cylinders instead of capsules to keep them connected as one object, rather than a mass of cables

**Comment by carpentre1** [comment]
Cables disconnect from plugs when receiving excessive tension.
Cables do not detect or respond appropriately to excessive tension from player hands pulling them apart; does not occur during normal gameplay, so pushing this issue to deal with during polish phase.
Game deploys and behaves as expected on Quest.
