### ISSUE TITLE
Test Issue: Screen goes black when people stand up from crouching

### ISSUE THREAD

**Issue by swarmsoflizards** [parkerhams/grandma-game#50]

**Comment by carpentre1** [comment]
I think this happened whenever the Quest's tracking failed to read the environment. It had intermittent troubles throughout the playtesting session and eventually decided the tracking was so unreliable that it completely disabled the boundary system of its own volition (and then re-enabled it later on). When the boundaries were disabled I think the issue no longer occurred, but that's not a solution - the boundaries are important!
I'll look into potential reasons that the tracking system can fail.

**Comment by carpentre1** [comment]
This issue hasn't been seen since that playtest. We'll reopen if we see it again.
