### ISSUE TITLE
Videos needed

### ISSUE THREAD

**Issue by carpentre1** [parkerhams/grandma-game#68]
Video clips we need to finish the game:

- [x] Band video with reduced volume

- [x] Banana video

- [x] Pancake video

- [x] Plate video

- [x] Credits video

**Comment by NervesOfJello** [comment]
Committing my available time to completing this task

**Comment by NervesOfJello** [comment]
Edits of videos have been completed! Uploading shortly

**Comment by NervesOfJello** [comment]
All videos added, will re-edit as necessary
