### ISSUE TITLE
Players spawn into the wall

### ISSUE THREAD

**Issue by swarmsoflizards** [parkerhams/grandma-game#82]

**Comment by carpentre1** [comment]
The player's current spawn position is in open space behind the TV stand, but if they move their head back they'll put their head through the wall. There's no way to completely prevent this, but if we added more space between the wall and TV stand it would be much less likely to occur. However, this would also widen the playspace and make it more difficult for players to connect everything. I'm not sure what the best solution is. It depends on how often this issue affects players.
